apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ecomdressstore
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: node-app
  template: 
    metadata: 
      labels:
        app: node-app
    spec:
      containers: 
        - name: ecomdressstore
          image: pkansif/ecom
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 3000  
      nodePort: 30003   
  type: NodePort
